import{WORLD,REGIONS,MONSTER_TYPES,createWorld,regionAt,clampPoint,circleHit,fuzzballUnlocked,portalUnlocked}from'./world.mjs';
import{saveLocal,loadLocal,clearLocal,hasLocal,shouldResetOnStart}from'./progress.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
const ui={health:$('health'),energy:$('energy'),echoes:$('echoes'),region:$('region'),objective:$('objective'),story:$('story-current'),log:$('story-log'),overlay:$('overlay'),overlayTitle:$('overlay-title'),overlayText:$('overlay-text'),start:$('start'),pause:$('pause'),save:$('save-progress'),load:$('load-progress'),clear:$('clear-progress'),progressStatus:$('progress-status')};
const pressed=new Set();let state,last=performance.now(),raf=0;
function progressMessage(text){if(ui.progressStatus)ui.progressStatus.textContent=text;}
function refreshProgressAvailability(announce=false){let available=false;try{available=hasLocal();}catch{}if(ui.load)ui.load.disabled=!available;if(ui.clear)ui.clear.disabled=!available;if(announce)progressMessage(available?'Local checkpoint available. Load only when you choose.':'No local checkpoint saved.');return available;}
function fresh(){const world=createWorld(640064);state={world,player:{x:360,y:330,radius:14,health:100,energy:100,invuln:0},playing:false,paused:false,gameOver:false,echoes:0,defeated:0,fuzzballFound:false,region:'sunmeadow',regionsSeen:new Set(['sunmeadow']),pulse:0,pulseCooldown:0,chapterComplete:false,lastStory:'The meadow is bright. Something beyond it is not.',time:0};ui.log.innerHTML='';addStory('The meadow is bright. Something beyond it is not.');syncUI();showOverlay('Explorer World','Move with WASD or arrow keys. Space sends a resonance pulse. E interacts. P pauses.','Enter the world');refreshProgressAvailability(true);}
function addStory(text){if(!text||state?.lastStory===text&&ui.log.children.length)return;state.lastStory=text;ui.story.textContent=text;const li=document.createElement('li');li.textContent=text;ui.log.prepend(li);while(ui.log.children.length>12)ui.log.lastElementChild.remove();}
function objective(){if(state.chapterComplete)return'Chapter One complete — keep exploring.';if(state.echoes<3)return`Collect ${3-state.echoes} more Echo Shard${3-state.echoes===1?'':'s'}.`;if(!state.fuzzballFound)return'Find Fuzzball inside The Anomaly.';if(state.echoes<6)return`Collect ${6-state.echoes} total Echo Shards.`;return'Enter the opened anomaly gate.';}
function syncUI(){ui.health.textContent=Math.max(0,Math.ceil(state.player.health));ui.energy.textContent=Math.max(0,Math.ceil(state.player.energy));ui.echoes.textContent=`${state.echoes} / 6`;ui.region.textContent=regionAt(state.player.x,state.player.y).name;ui.objective.textContent=objective();ui.pause.textContent=state.paused?'Resume':'Pause';}
function showOverlay(title,text,button){ui.overlayTitle.textContent=title;ui.overlayText.textContent=text;ui.start.textContent=button;ui.overlay.hidden=false;}
function hideOverlay(){ui.overlay.hidden=true;canvas.focus();}
function start(){if(shouldResetOnStart(state))fresh();state.playing=true;state.paused=false;hideOverlay();syncUI();}
function togglePause(){if(!state.playing||state.gameOver)return;state.paused=!state.paused;if(state.paused)showOverlay('Paused','The world is holding its breath.','Resume');else hideOverlay();syncUI();}
function saveProgress(){if(state.gameOver){progressMessage('Restart the chapter before saving.');return;}try{saveLocal(state);refreshProgressAvailability(false);progressMessage('Progress saved in this browser.');}catch(error){progressMessage(`Save unavailable: ${error?.message||error}`);}}
function loadProgress(){try{const loaded=loadLocal();if(!loaded){refreshProgressAvailability(true);return;}state=loaded;pressed.clear();ui.log.innerHTML='';addStory(state.lastStory||'Local checkpoint restored.');syncUI();showOverlay('Progress loaded',state.chapterComplete?'Chapter One is complete. Continue exploring from this checkpoint.':'Your browser-local checkpoint is restored.','Continue');refreshProgressAvailability(false);progressMessage('Local progress loaded.');}catch(error){progressMessage(`Could not load progress: ${error?.message||error}`);}}
function clearProgress(){try{clearLocal();refreshProgressAvailability(false);progressMessage('Local checkpoint cleared.');}catch(error){progressMessage(`Could not clear progress: ${error?.message||error}`);}}
function inputVector(){let x=0,y=0;if(pressed.has('ArrowLeft')||pressed.has('a'))x--;if(pressed.has('ArrowRight')||pressed.has('d'))x++;if(pressed.has('ArrowUp')||pressed.has('w'))y--;if(pressed.has('ArrowDown')||pressed.has('s'))y++;if(x&&y){x*=Math.SQRT1_2;y*=Math.SQRT1_2;}return{x,y};}
function pulse(){if(!state.playing||state.paused||state.gameOver||state.player.energy<22||state.pulseCooldown>0)return;state.player.energy-=22;state.pulse=.28;state.pulseCooldown=.62;for(const m of state.world.monsters){if(!m.alive)continue;const dx=m.x-state.player.x,dy=m.y-state.player.y;if(dx*dx+dy*dy<150*150){m.hp-=42;if(m.hp<=0){m.alive=false;state.defeated++;if(state.defeated===1)addStory('The first monster breaks into harmless motes. The world notices.');}}}}
function interact(){if(!state.playing||state.paused)return;const f=state.world.fuzzball;if(fuzzballUnlocked(state)&&!state.fuzzballFound&&circleHit(state.player,f,42)){state.fuzzballFound=true;f.found=true;addStory('FUZZBALL FOUND — a soft impossible artifact asks: “Where does a classical analogy stop being valid quantum reasoning?” It offers a question, not an answer.');if(portalUnlocked(state))state.world.portal.active=true;syncUI();return;}const p=state.world.portal;if(portalUnlocked(state)&&circleHit(state.player,p,45)){state.chapterComplete=true;state.playing=false;addStory('The gate accepts the remainder. Chapter One is complete; the larger shared world remains to be built.');showOverlay('Chapter One complete','You crossed the regions, survived the monsters, found Fuzzball, and opened the gate. You can keep exploring this shard.','Keep exploring');syncUI();}}
function update(dt){if(!state.playing||state.paused||state.gameOver)return;state.time+=dt;const p=state.player,v=inputVector(),speed=210;p.x+=v.x*speed*dt;p.y+=v.y*speed*dt;Object.assign(p,clampPoint(p.x,p.y,22));p.energy=Math.min(100,p.energy+18*dt);p.invuln=Math.max(0,p.invuln-dt);state.pulse=Math.max(0,state.pulse-dt);state.pulseCooldown=Math.max(0,state.pulseCooldown-dt);
  const reg=regionAt(p.x,p.y);if(reg.id!==state.region){state.region=reg.id;if(!state.regionsSeen.has(reg.id)){state.regionsSeen.add(reg.id);addStory(reg.story);}}
  for(const e of state.world.echoes){if(!e.collected&&circleHit(p,e,5)){e.collected=true;state.echoes++;if(state.echoes===1)addStory('An Echo Shard remembers a sound you never made.');else if(state.echoes===3)addStory('Three shards resonate. Something fuzzy has become detectable inside The Anomaly.');else if(state.echoes===6)addStory(state.fuzzballFound?'Six shards answer Fuzzball. A gate opens in the north of The Anomaly.':'Six shards sing, but the hidden artifact is still missing.');}}
  if(portalUnlocked(state))state.world.portal.active=true;
  for(const m of state.world.monsters){if(!m.alive)continue;const spec=MONSTER_TYPES[m.type],dx=p.x-m.x,dy=p.y-m.y,d=Math.hypot(dx,dy)||1;m.cooldown=Math.max(0,m.cooldown-dt);let vx=0,vy=0;if(d<390){vx=dx/d;vy=dy/d;if(m.type==='prismmoth'){vx+=Math.sin(state.time*5+m.phase)*.45;vy+=Math.cos(state.time*4+m.phase)*.45;}if(m.type==='clockstag'&&d<190){vx*=1.45;vy*=1.45;}}else{vx=Math.cos(state.time*.55+m.phase)*.32;vy=Math.sin(state.time*.47+m.phase)*.32;}m.x+=vx*spec.speed*dt;m.y+=vy*spec.speed*dt;const q=clampPoint(m.x,m.y,35);m.x=q.x;m.y=q.y;if(circleHit(p,m,2)&&p.invuln<=0){p.health-=spec.damage;p.invuln=.8;const kx=dx/d,ky=dy/d;p.x+=kx*36;p.y+=ky*36;addStory(`${spec.name} hit you. The world is dangerous, not decorative.`);if(p.health<=0){p.health=0;state.gameOver=true;state.playing=false;showOverlay('You fell','The world keeps moving. Restart the chapter and try another path.','Restart');}}}
  syncUI();}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(320,Math.round(r.width)),h=Math.max(240,Math.round(r.width*10/16));if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}return{w,h};}
function worldToScreen(x,y,cam,w,h){return{x:x-cam.x+w/2,y:y-cam.y+h/2};}
function draw(){const{w,h}=resize(),p=state.player,cam={x:Math.max(w/2,Math.min(WORLD.width-w/2,p.x)),y:Math.max(h/2,Math.min(WORLD.height-h/2,p.y))};ctx.clearRect(0,0,w,h);
  for(const r of REGIONS){const a=worldToScreen(r.x,r.y,cam,w,h);ctx.fillStyle=r.ground;ctx.fillRect(a.x,a.y,r.w,r.h);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.strokeRect(a.x,a.y,r.w,r.h);ctx.fillStyle='rgba(255,255,255,.12)';ctx.font='700 28px system-ui';ctx.fillText(r.name,a.x+24,a.y+42);}
  for(const d of state.world.decor){const s=worldToScreen(d.x,d.y,cam,w,h);if(s.x<-10||s.x>w+10||s.y<-10||s.y>h+10)continue;const r=REGIONS.find(x=>x.id===d.region);ctx.fillStyle=r.accent;ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(s.x,s.y,d.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
  for(const e of state.world.echoes){if(e.collected)continue;const s=worldToScreen(e.x,e.y,cam,w,h),z=9+Math.sin(state.time*3+e.phase)*2;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.PI/4);ctx.fillStyle='#d7fff2';ctx.fillRect(-z/2,-z/2,z,z);ctx.restore();}
  const f=state.world.fuzzball;if(fuzzballUnlocked(state)&&!state.fuzzballFound){const s=worldToScreen(f.x,f.y,cam,w,h);ctx.fillStyle='#d7a9ff';ctx.beginPath();for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=18+(i%2?7:2)+Math.sin(state.time*4+i)*2,px=s.x+Math.cos(a)*r,py=s.y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fill();ctx.fillStyle='#251331';ctx.beginPath();ctx.arc(s.x-6,s.y-3,2.2,0,6.3);ctx.arc(s.x+6,s.y-3,2.2,0,6.3);ctx.fill();}
  const gate=state.world.portal;if(gate.active){const s=worldToScreen(gate.x,gate.y,cam,w,h);ctx.strokeStyle='#caa8ff';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(s.x,s.y,26,48,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#83ffe1';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(s.x,s.y,15+Math.sin(state.time*4)*4,37,0,0,Math.PI*2);ctx.stroke();}
  for(const m of state.world.monsters){if(!m.alive)continue;const spec=MONSTER_TYPES[m.type],s=worldToScreen(m.x,m.y,cam,w,h);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(state.time*.4+m.phase);ctx.fillStyle=spec.color;if(m.type==='prismmoth'){for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.ellipse(12,0,15,7,0,0,6.3);ctx.fill();}}else if(m.type==='clockstag'){ctx.fillRect(-15,-15,30,30);ctx.strokeStyle='#f4df9c';ctx.beginPath();ctx.moveTo(-10,-13);ctx.lineTo(-20,-28);ctx.moveTo(10,-13);ctx.lineTo(20,-28);ctx.stroke();}else{ctx.beginPath();ctx.arc(0,0,spec.radius,0,6.3);ctx.fill();}ctx.restore();if(m.hp<m.maxHp){ctx.fillStyle='#2a1010';ctx.fillRect(s.x-20,s.y-spec.radius-12,40,4);ctx.fillStyle='#ff8a8a';ctx.fillRect(s.x-20,s.y-spec.radius-12,40*m.hp/m.maxHp,4);}}
  const ps=worldToScreen(p.x,p.y,cam,w,h);if(state.pulse>0){ctx.strokeStyle='rgba(145,230,192,.8)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(ps.x,ps.y,150*(1-state.pulse/.28),0,6.3);ctx.stroke();}ctx.save();ctx.translate(ps.x,ps.y);ctx.rotate(Math.atan2((pressed.has('ArrowDown')||pressed.has('s'))-(pressed.has('ArrowUp')||pressed.has('w')),(pressed.has('ArrowRight')||pressed.has('d'))-(pressed.has('ArrowLeft')||pressed.has('a')))||0);ctx.fillStyle=p.invuln>0&&Math.floor(state.time*12)%2?'#fff':'#91e6c0';ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-12,-11);ctx.lineTo(-7,0);ctx.lineTo(-12,11);ctx.closePath();ctx.fill();ctx.restore();
  ctx.fillStyle='rgba(8,12,18,.22)';ctx.fillRect(0,0,w,h);const day=(Math.sin(state.time/10)+1)/2;ctx.fillStyle=`rgba(5,8,20,${.22*(1-day)})`;ctx.fillRect(0,0,w,h);}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();raf=requestAnimationFrame(loop);}
function keyName(e){return e.key.length===1?e.key.toLowerCase():e.key;}
addEventListener('keydown',e=>{const k=keyName(e);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','w','a','s','d','e','p'].includes(k))e.preventDefault();if(k===' '){pulse();return;}if(k==='e'){interact();return;}if(k==='p'){togglePause();return;}pressed.add(k);});addEventListener('keyup',e=>pressed.delete(keyName(e)));
for(const b of document.querySelectorAll('[data-key]')){const k=b.dataset.key;const on=e=>{e.preventDefault();pressed.add(k);};const off=e=>{e.preventDefault();pressed.delete(k);};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off);}
ui.start.addEventListener('click',start);$('pause').addEventListener('click',togglePause);$('restart').addEventListener('click',fresh);$('pulse').addEventListener('click',pulse);$('interact').addEventListener('click',interact);ui.save?.addEventListener('click',saveProgress);ui.load?.addEventListener('click',loadProgress);ui.clear?.addEventListener('click',clearProgress);canvas.addEventListener('pointerdown',()=>{if(!state.playing&&!state.paused)start();});
fresh();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);
