import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,stat,mkdtemp,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import {resolve,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=fileURLToPath(new URL('../../',import.meta.url));
const profile=await mkdtemp(resolve(tmpdir(),'context-horizon-browser-'));
let chrome,socket,seq=0;const pending=new Map();
const server=createServer(async(req,res)=>{try{let path=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(path!==resolve(root)&&!path.startsWith(resolve(root)+sep))throw Error('path');if((await stat(path)).isDirectory())path=resolve(path,'index.html');const body=await readFile(path);const type=({'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.mjs':'text/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.json':'application/json;charset=utf-8'})[extname(path)]||'text/plain;charset=utf-8';res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});
function send(method,params={},sessionId){return new Promise((resolvePromise,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error(`CDP timeout: ${method}`));},15000);pending.set(id,{resolve:resolvePromise,reject,timer});socket.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));});}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
  const endpoint=await new Promise((resolvePromise,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Chrome did not start')),20000);chrome=spawn(process.env.CHROME_BIN||'google-chrome',['--headless=new','--no-sandbox','--disable-dev-shm-usage','--no-first-run','--disable-background-networking','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});chrome.once('error',e=>{clearTimeout(timer);reject(e);});chrome.stderr.on('data',chunk=>{output=(output+chunk).slice(-12000);const m=output.match(/DevTools listening on (ws:\/\/\S+)/);if(m){clearTimeout(timer);resolvePromise(m[1]);}});});
  socket=new WebSocket(endpoint);await new Promise((r,j)=>{socket.addEventListener('open',r,{once:true});socket.addEventListener('error',j,{once:true});});socket.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(!msg.id)return;const slot=pending.get(msg.id);if(!slot)return;pending.delete(msg.id);clearTimeout(slot.timer);if(msg.error)slot.reject(Error(JSON.stringify(msg.error)));else slot.resolve(msg.result);});
  const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});const call=(method,params={})=>send(method,params,sessionId);await call('Page.enable');await call('Runtime.enable');await call('DOM.enable');
  const evaluate=async(fn,...args)=>{const result=await call('Runtime.evaluate',{expression:`(${fn.toString()})(...${JSON.stringify(args)})`,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;};
  async function navigate(path){const url=origin+path;await call('Page.navigate',{url});for(let i=0;i<120;i++){const ready=await evaluate(url=>location.href===url&&document.readyState!=='loading',url).catch(()=>false);if(ready)return url;await sleep(75);}throw Error(`page did not load: ${path}`);}
  async function waitPanel(){for(let i=0;i<120;i++){const x=await evaluate(()=>({panel:!!document.getElementById('context-horizon-panel'),links:document.querySelectorAll('#context-horizon-links a').length,route:document.getElementById('context-horizon-panel')?.dataset.routeId||''}));if(x.panel&&x.links>0)return x;await sleep(75);}throw Error('Context Horizon panel did not initialize');}

  const pages=[['/research/projects/','research-projects'],['/play/','play-hub'],['/play/mmo/simple/','mmo-simple'],['/play/mmo/forge.html','arcade-forge'],['/play/mmo/simple/visual-samples/','visual-samples'],['/play/explorer-world/','explorer-world'],['/history/','history-root']];
  for(const[path,route]of pages){await navigate(path);const panel=await waitPanel();assert.equal(panel.route,route,path);const a11y=await evaluate(()=>{const a=document.querySelector('#context-horizon-links a');a?.focus();return{active:document.activeElement===a,label:a?.getAttribute('aria-label')||'',fallback:[...document.querySelectorAll('a')].some(a=>/Context Horizon/.test(a.textContent))};});assert.equal(a11y.active,true,`${path} ranked link not focusable`);assert.match(a11y.label,/Navigation relevance is not evidence or authority/);assert.equal(a11y.fallback,true,`${path} missing direct Context Horizon link`);}

  await navigate('/play/mmo/simple/');await waitPanel();const before=await evaluate(async()=>{const r=await import('/navigation/context-horizon/route-registry.mjs');const x=r.getRoute('research-projects');return{owner:x.ownerDomain,epi:x.epistemicRole,prov:x.provenance.status};});
  const ambiguity=await evaluate(()=>{const input=document.getElementById('context-horizon-intent');input.value='research game';input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('.context-horizon-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));return true;});assert.equal(ambiguity,true);for(let i=0;i<80;i++){if(await evaluate(()=>!document.getElementById('context-horizon-question')?.hidden))break;if(i===79)throw Error('research/game discriminator did not appear');await sleep(50);}const question=await evaluate(()=>({text:document.getElementById('context-horizon-question').textContent,buttons:[...document.querySelectorAll('#context-horizon-question button')].map(b=>b.textContent)}));assert.match(question.text,/original research work/i);assert.match(question.text,/game surface/i);assert.equal(question.buttons.length,2);
  await evaluate(()=>[...document.querySelectorAll('#context-horizon-question button')].find(b=>/Original research work/.test(b.textContent))?.click());await sleep(100);const after=await evaluate(async()=>{const r=await import('/navigation/context-horizon/route-registry.mjs');const x=r.getRoute('research-projects');return{owner:x.ownerDomain,epi:x.epistemicRole,prov:x.provenance.status,top:document.querySelector('#context-horizon-links a')?.getAttribute('href')||''};});assert.deepEqual({owner:after.owner,epi:after.epi,prov:after.prov},before);assert.match(after.top,/research\/projects/);

  await call('Emulation.setDeviceMetricsOverride',{width:320,height:900,deviceScaleFactor:1,mobile:false});const narrow=await evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(narrow.scroll<=narrow.width+1,`Context Horizon overflow at 320px: ${JSON.stringify(narrow)}`);await call('Emulation.setDeviceMetricsOverride',{width:1100,height:900,deviceScaleFactor:1,mobile:false});

  await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await navigate('/');const rootPanel=await waitPanel();assert.equal(rootPanel.route,'conscience-root');const rootVisual=await evaluate(()=>({cores:document.querySelectorAll('.space-core').length,hairLayer:document.querySelectorAll('#context-horizon-hairs').length,pulses:document.querySelectorAll('#context-horizon-hairs .context-hair-pulse').length,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));assert.equal(rootVisual.cores,1,'Context Horizon must reuse the existing Space Lens center');assert.equal(rootVisual.hairLayer,1);assert.equal(rootVisual.pulses,0);assert.equal(rootVisual.reduced,true);await call('Emulation.setEmulatedMedia',{features:[]});

  await call('Emulation.setScriptExecutionDisabled',{value:true});for(const path of ['/research/projects/','/play/','/play/mmo/simple/','/history/','/navigation/context-horizon/']){await call('Page.navigate',{url:origin+path});await sleep(150);const {root:doc}=await call('DOM.getDocument',{depth:1,pierce:true});const {outerHTML}=await call('DOM.getOuterHTML',{nodeId:doc.nodeId});assert.match(outerHTML,/Context Horizon|All pages and preserved works/i,path);assert.match(outerHTML,/href=/,path);}await call('Emulation.setScriptExecutionDisabled',{value:false});

  console.log('PASS Context Horizon browser: peer routes, discriminator, keyboard focus, reduced motion, single Space Lens center, no-JS fallback, and epistemic isolation');
}finally{
  try{socket?.close();}catch{}
  if(chrome&&chrome.exitCode===null){const exited=new Promise(resolveExit=>chrome.once('exit',resolveExit));try{chrome.kill('SIGKILL');}catch{}await Promise.race([exited,sleep(3000)]);}
  if(server.listening)await new Promise(resolveClose=>server.close(resolveClose));
  let lastError=null;for(let i=0;i<8;i++){try{await rm(profile,{recursive:true,force:true});lastError=null;break;}catch(error){lastError=error;await sleep(150*(i+1));}}if(lastError)throw lastError;
}
