const $=id=>document.getElementById(id);
const concept={
  language:{exact:'Language Quality = meaning preserved / cognitive effort',plain:'Language quality rises when meaning survives while cognitive effort falls.',mnemonic:'Meaning maintained, mental mileage minimized.',boundary:'This is a working quality measure for language and interface design, not a universal scientific law.'},
  irpo:{exact:'O = F(I, R, P)',plain:'Output depends on what we have, what relation matters, and what plan we actually try.',mnemonic:'Input inspected. Relation revealed. Plan performed. Output observed.',boundary:'I, R, P, O is a planning and reasoning interface. The function F is task-specific rather than a fixed equation.'},
  np:{exact:'x ∈ L ⇔ ∃w, |w| ≤ poly(|x|) and V(x,w)=1 in polynomial time',plain:'For an N P language, a yes instance has a polynomial-size witness that a polynomial-time verifier can check.',mnemonic:'Witness written, verifier works; search may still swell.',boundary:'This is the standard witness-verifier characterization of NP. It does not prove that P differs from NP.'},
  pnp:{exact:'P ?= NP',plain:'The open question asks whether every problem whose yes answers can be verified efficiently can also be solved efficiently.',mnemonic:'Proof pending. Polynomial paths remain parted or perhaps paired.',boundary:'P versus NP remains open. Pattern, compression, analogy, or a fast result on selected instances is not a proof.'},
  carrier:{exact:'source —transform→ target + remainder',plain:'Move an object across a representation only after declaring the source, transform, target, what must survive, and what was lost.',mnemonic:'Carrier crosses context; consequence continues; remainder remains.',boundary:'A successful transport does not automatically transfer truth, proof, semantics, or authority.'},
  repair:{exact:"[S′](TgI)=0 under minimal repair g",plain:'Treat S prime under a minimally repaired transform as a research expression to test, not as a theorem already earned.',mnemonic:'Smallest shift, strict test, surviving structure.',boundary:'This is project notation and a hypothesis-generating expression. It needs explicit definitions and executed verification before any stronger mathematical claim.'},
  human:{exact:'H = Context(Needs, Observers, Knowledge, Time, Cost, Ethics, Goals)',plain:'Model a human situation with needs, observers, available knowledge, time, cost, ethics, and goals kept visible.',mnemonic:'Humans have hunger, history, horizons, and hard limits.',boundary:'This is a general working model for keeping human constraints present. It is not a scoring function or a predictive law of people.'},
  babel:{exact:'verified subject / obligation ≠ implementation carrier',plain:'Keep the subject and its obligations fixed while allowing the carrier, hierarchy, or index to change if behavior survives comparison.',mnemonic:'Subject stays; structure shifts; semantics survive.',boundary:'Carrier simplification is valid only inside the tested subject and obligations. It is not a global minimality result.'},
  utf:{exact:'UTF-8 bytes → exact Float64 carrier coordinates → exact UTF-8 bytes',plain:'The codec can carry tested U T F eight bytes through exact float sixty four coordinates and reconstruct those bytes exactly.',mnemonic:'Bytes become bearings; bearings bring bytes back.',boundary:'Bit identity establishes transport identity only. It does not establish semantic truth, compression, encryption, or mathematical equivalence.'},
  hodge:{exact:'rational Hodge classes ?= algebraic cycle classes',plain:'The Hodge program asks when rational cohomology classes of the right Hodge type come from algebraic cycles.',mnemonic:'Classes call for cycles; coincidence cannot close the conjecture.',boundary:'The Hodge conjecture remains open in general. Computational patterns and cross-project analogies can guide experiments but cannot replace proof.'}
};
let mode='period';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
function customMnemonic(text){const words=clean(text).split(/[^\p{L}\p{N}′']+/u).filter(Boolean);if(!words.length)return'Carry the concept clearly; compare what changes.';const initial=(words.find(w=>/^\p{L}/u.test(w))?.[0]||'C').toUpperCase();const banks={C:['carry','compare','compress','counterprobe'],M:['meaning','memory','measure','map'],S:['source','structure','semantics','survive'],P:['plan','probe','preserve','prove'],R:['relation','remainder','repair','retest'],H:['human','history','horizon','hold'],W:['witness','work','weigh','widen'],T:['transform','test','trace','truth']};const bank=banks[initial]||banks.C;return `${bank[0]} the claim; ${bank[1]} the change; ${bank[2]} the consequence; ${bank[3]} only what survives.`;}
function current(){const raw=$('custom').value.trim();if(raw){return{exact:raw,plain:globalThis.VoiceAnywhere?.toSpeakable(raw)||raw,mnemonic:customMnemonic(raw),boundary:'Custom input is preserved as user-supplied notation. The mnemonic rephrasing is a memory aid, not evidence of equivalence.'};}return concept[$('concept').value];}
function communicate(c){return `${c.plain}\n\nMemory hook: ${c.mnemonic}\n\nBoundary: ${c.boundary}`;}
function explode(c){return[`Exact: ${c.exact}`,`Plain: ${c.plain}`,`Mnemonic: ${c.mnemonic}`,`Carrier check: what is preserved, changed, and left over?`,`Human check: who benefits, who bears cost, and what remains unknown?`,`Claim check: ${c.boundary}`].join('\n');}
function render(){const c=current();let exact=c.exact,plain=c.plain,mnemonic=c.mnemonic,boundary=c.boundary;if(mode==='enter'){plain=`I — ${c.exact}\nR — ${c.plain}\nP — Test the smallest consequential distinction.\nO — Record observation, change, and remainder.`;mnemonic=`Input inspected. Relation revealed. Plan performed. Output observed. ${c.mnemonic}`;}else if(mode==='communicate'){plain=communicate(c);mnemonic='Communicate clearly; keep the exact form and boundary available for anyone who needs to inspect them.';}else if(mode==='explode'){plain=explode(c);mnemonic=`${c.mnemonic}\nCross it with source, carrier, human, cost, time, evidence, and counterexample.`;}$('exact').textContent=exact;$('plain').textContent=plain;$('mnemonic').textContent=mnemonic;$('boundary').textContent=boundary;}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));render();}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('transform').addEventListener('click',render);$('concept').addEventListener('change',render);$('custom').addEventListener('input',()=>{if(mode==='period')render();});
$('speak').addEventListener('click',()=>globalThis.VoiceAnywhere?.speak($('plain').textContent,{lang:document.documentElement.lang||navigator.language}));
const chorus=$('chorus');for(const line of globalThis.ResearchSong?.lines||[]){const p=document.createElement('p');p.textContent=line;chorus.appendChild(p);}render();
