import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = path => readFile(new URL(path, import.meta.url), 'utf8');
const [index, style, forge, forgeJs, gameJs, saveRuntimeJs, current, canon, linkages, linkagesJsonText, projectsText, sampleText, contractText] = await Promise.all([
  read('index.html'), read('style.css'), read('forge.html'), read('forge.js'), read('game.js'), read('save-runtime.js'), read('CURRENT.md'), read('REALITY_CANON.md'), read('LINKAGES.md'), read('linkages.json'), read('../projects.json'), read('plugins/duck-rescue.json'), read('plugin-contract.json')
]);

assert.match(current, /implemented now/i);
assert.match(current, /Portable local player state/i);
assert.match(current, /Grounded Starter Pack/i);
assert.match(current, /10 explicit mini-game\/activity slots/i);
assert.match(current, /two additional movement\/reaction activities/i);
assert.match(current, /LOCAL_SAVE != SERVER_AUTHORITY/);
assert.match(current, /TEST_CONFIGURED != TEST_OBSERVED_PASSING/);
assert.match(current, /Not implemented yet/i);
assert.match(current, /CURRENT\.md → RMAO_WORLD_CANON\.md \/ rmao-world-contract\.json → REALITY_CANON\.md/);
assert.match(canon, /real before it becomes impossible/i);
assert.match(canon, /OBSERVATION != PROCESSED_SCIENCE_IMAGE != GAME_RECONSTRUCTION/);
assert.match(canon, /older MMO aesthetic or content note conflicts.*this file wins/is);
assert.match(canon, /Event Horizon Telescope M87\*/);
assert.match(canon, /James Webb Space Telescope/);
assert.match(index, /CURRENT\.md/);
assert.match(index, /Mercer &amp; Red Street/);
assert.match(index, /IN-GAME RECONSTRUCTION · NOT TELESCOPE DATA/);
assert.match(index, /Roof observatory/i);
assert.match(index, /World time and conditions are fictional game state/i);
assert.match(index, /eventhorizontelescope\.org/);
assert.match(index, /science\.nasa\.gov/);
assert.match(index, /plugin-runtime\.js/);
assert.match(index, /save-runtime\.js/);
assert.match(index, /Locally installed cabinets/);
assert.match(index, /id="plugin-games"/);
assert.match(index, /id="save-local"/);
assert.match(index, /Nothing loads automatically/);
assert.match(style, /--brick:/); assert.match(style, /--concrete:/); assert.match(style, /\.street-scene/); assert.match(style, /\.sky-window/); assert.match(style, /\.black-hole/);
assert.match(forge, /ordinary place\/object\/activity first/i); assert.match(forge, /MAKER GARAGE/);
assert.match(forgeJs, /Grounded Starter Pack/);
assert.match(forgeJs, /market-closing-shift/);
assert.match(forgeJs, /bus-transfer-seven/);
assert.match(forgeJs, /workshop-sort/);
assert.match(forgeJs, /observatory-label-check/);
assert.match(forgeJs, /repair-bench-remix/);
assert.match(forgeJs, /fuzzball-question-or-claim/);
assert.match(forgeJs, /question is not promoted into evidence or proof/i);
assert.match(forgeJs, /Untimed maker activity/i);
assert.match(forgeJs, /runtime\.install/);
assert.match(forgeJs, /corner market/); assert.match(forgeJs, /bus stop/); assert.match(forgeJs, /rooftop observatory/); assert.doesNotMatch(forgeJs, /Floating Library/);
assert.match(gameJs, /Conscience64MMOPlugins/);
assert.match(gameJs, /Conscience64MMOSave/);
assert.match(gameJs, /refreshPlugins/);
assert.match(gameJs, /snapshotState/);
assert.match(gameJs, /applySave/);
assert.match(gameJs, /plugins\.validate/);
assert.match(gameJs, /Completed local plug-in/);
assert.match(gameJs, /no multiplayer or prize authority/i);
assert.match(gameJs, /Use untimed route/);
assert.match(gameJs, /Redline — untimed route/);
assert.match(gameJs, /Finished Redline using the untimed route/);
assert.match(gameJs, /There is no penalty and no timer pushing you forward/);
assert.match(saveRuntimeJs, /conscience64\.mmo\.save\/v1/);
assert.match(saveRuntimeJs, /state\.chronicle too long/);
assert.match(linkages, /Load order/i); assert.match(linkages, /CURRENT\.md/); assert.match(linkages, /six validated data-only recipes/i); assert.match(linkages, /Repair Bench Remix/); assert.match(linkages, /Fuzzball: Question or Claim\?/); assert.match(linkages, /Grounded Starter Pack chain/i); assert.match(linkages, /STARTER_PACK_INSTALL != SERVER_AUTHORITY/); assert.match(linkages, /Portable local-life chain/i); assert.match(linkages, /REALITY_CANON\.md/);
const linkageGraph = JSON.parse(linkagesJsonText);
assert.equal(linkageGraph.version, '1.4.0');
assert.ok(linkageGraph.nodes.some(node=>node.id==='current-state' && node.path==='CURRENT.md'));
assert.ok(linkageGraph.nodes.some(node=>node.id==='grounded-starter-pack' && node.path==='forge.js'));
assert.ok(linkageGraph.nodes.some(node=>node.id==='save-runtime' && node.path==='save-runtime.js'));
assert.ok(linkageGraph.edges.some(edge=>edge.from==='arcade-forge' && edge.to==='grounded-starter-pack' && edge.relation==='offers-explicit-install-of'));
assert.ok(linkageGraph.edges.some(edge=>edge.from==='mmo-browser-test' && edge.to==='grounded-starter-pack' && edge.relation==='tests-forge-install-and-mmo-discovery'));
assert.ok(linkageGraph.edges.some(edge=>edge.from==='current-state' && edge.to==='release-plan' && edge.relation==='distinguishes-current-from-roadmap'));
assert.ok(linkageGraph.edges.some(edge=>edge.from==='mmo-browser-test' && edge.to==='save-runtime'));
assert.ok(linkageGraph.invariants.includes('LOCAL_SAVE != SERVER_AUTHORITY'));
assert.ok(linkageGraph.invariants.includes('STARTER_PACK_INSTALL != SERVER_AUTHORITY'));
assert.ok(linkageGraph.invariants.includes('TEST_CONFIGURED != TEST_OBSERVED_PASSING'));
const projects = JSON.parse(projectsText); const mmo = projects.projects.find(project => project.id === 'mmo'); assert.ok(mmo); assert.equal(mmo.source, 'mmo/REALITY_CANON.md'); assert.match(mmo.purpose, /grounded real-world-feeling/i);
const sample = JSON.parse(sampleText); assert.equal(sample.schema, 'conscience64.mmo.plugin/v1'); assert.match(sample.prompt, /corner market|market display/i); assert.match(sample.description, /grounded-reality-first/i);
const contract = JSON.parse(contractText); assert.equal(contract.contentDirection.canonical, 'REALITY_CANON.md'); assert.equal(contract.contentDirection.anomalyRequired, false);
console.log('PASS MMO reality canon: current-state boundary, grounded world, astronomy boundary, Forge generation, six-game Grounded Starter Pack including maker + Fuzzball, machine/human linkages, main-MMO plug-in discovery, portable save boundary, untimed Redline route, registry and evidence boundaries');
