import {advanceSecret, normalizeProfile, makeFrontier, eventInterval} from './core.mjs';
const c=document.querySelector('#world'),ctx=c.getContext('2d'),ui=id=>document.getElementById(id);
let W=0,H=0,DPR=1,last=performance.now(),frontierIndex=0;
const keys=new Set(),pointer={active:false,x:0,y:0},ghosts=new Map(),mobs=[],signals=[];
let profile;try{profile=normalizeProfile(JSON.parse(localStorage.getItem('df-mmorpg')||'{}'))}catch{profile=normalizeProfile()}
const state={t:0,epoch:0,carrier:0,chaos:1,eventT:0,eventEvery:eventInterval(profile),secret:[],fuzzball:profile.discoveries.includes('Fuzzball'),frontier:null,motion:false};
const player={id:crypto.randomUUID(),name:'Explorer-'+Math.floor(Math.random()*10000),x:0,y:0,vx:0,vy:0,hp:100,xp:0,level:1,phase:0};
function save(){localStorage.setItem('df-mmorpg',JSON.stringify(profile))}
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function log(s){const d=document.createElement('div');d.className='logline';d.textContent='› '+s;ui('log').prepend(d);while(ui('log').children.length>12)ui('log').lastChild.remove()}
function addMob(kind='drifter'){mobs.push({kind,x:player.x+(Math.random()-.5)*1800,y:player.y+(Math.random()-.5)*1800,r:kind==='boss'?30:8+Math.random()*13,hp:kind==='boss'?300:25+Math.random()*45,speed:kind==='boss'?20:6+Math.random()*8})}
function addSignal(){signals.push({x:player.x+(Math.random()-.5)*2200,y:player.y+(Math.random()-.5)*2200,v:1+Math.floor(Math.random()*4)})}
for(let i=0;i<60;i++)addMob(i%17===0?'beast':'drifter');for(let i=0;i<35;i++)addSignal();
const eventNames=['Gravity blinked','A city spawned upside-down','Every portal changed its destination','The rain began falling sideways','A boss arrived from a future patch','The map split into contradictory histories','The moon requested a party invite','All shadows formed a guild'];
function mutateWorld(){state.epoch++;state.eventT=0;state.chaos=.65+Math.random()*1.9;state.eventEvery=eventInterval(profile);profile.events++;for(let i=0;i<4;i++)addMob();for(let i=0;i<2;i++)addSignal();if(Math.random()<.25)addMob('boss');log('WORLD EVENT: '+eventNames[Math.floor(Math.random()*eventNames.length)]);save()}
function unlockFuzzball(){if(state.fuzzball)return;state.fuzzball=true;if(!profile.discoveries.includes('Fuzzball'))profile.discoveries.push('Fuzzball');save();log('??? FUZZBALL MATERIALIZED BETWEEN CARRIERS ???');openFrontier()}
function secretStep(k){const r=advanceSecret(state.secret,k);state.secret=r.buffer;if(r.unlocked)unlockFuzzball()}
function openFrontier(){state.frontier=makeFrontier(frontierIndex++);const p=state.frontier;ui('frontier').textContent=`FUZZBALL // ${p.name} — ${p.q} Boundary: ${p.boundary} Probe: ${p.probe} Status: ${p.status}.`;log('Quantum Frontier opened: '+p.name)}
function pulse(){profile.pulses++;let kills=0;for(const m of mobs){if(Math.hypot(m.x-player.x,m.y-player.y)<145){m.hp-=26+player.level*2;if(m.hp<=0){kills++;player.xp+=m.kind==='boss'?80:8}}}if(kills)log(`Pulse collapsed ${kills} hostile pattern${kills===1?'':'s'}.`);save()}
function interact(){let hit=-1,bd=90;signals.forEach((s,i)=>{const d=Math.hypot(s.x-player.x,s.y-player.y);if(d<bd){bd=d;hit=i}});if(hit>=0){const [s]=signals.splice(hit,1);player.xp+=s.v*5;profile.signals++;addSignal();log('Signal recovered +'+s.v);if(state.fuzzball&&profile.signals%3===0)openFrontier();save();return}log('Nothing close enough to interact with.')}
function phase(){player.phase=1.1;log('Phase shift.')}
function shout(){broadcast({type:'shout',text:`${player.name}: THE FIELD IS ALIVE`});log('You shouted across the local shard.')}
function setCarrier(n){state.carrier=n;log('Carrier lens: '+['geometry','semantic','rhythm'][n])}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);secretStep(k);if(e.code==='Space'){e.preventDefault();pulse()}else if(k==='e')interact();else if(k==='q')phase();else if(k==='r')shout();else if('123'.includes(k))setCarrier(+k-1);else if(k==='m')toggleMotion();else if(k==='v')toggleSpeech()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
c.addEventListener('pointerdown',e=>{pointer.active=true;pointer.x=e.clientX;pointer.y=e.clientY;c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(pointer.active){pointer.x=e.clientX;pointer.y=e.clientY}});c.addEventListener('pointerup',()=>pointer.active=false);c.addEventListener('dblclick',pulse);
async function toggleMotion(){if(state.motion){state.motion=false;log('Motion control off.');return}try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('permission')}state.motion=true;log('Motion control on.')}catch{log('Motion control unavailable or denied.')}}
addEventListener('devicemotion',e=>{if(!state.motion)return;const a=e.accelerationIncludingGravity||{};player.vx+=Math.max(-3,Math.min(3,a.x||0))*.05;player.vy-=Math.max(-3,Math.min(3,a.y||0))*.05;profile.input.motion++});
let recognition=null;function toggleSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){log('Speech recognition is not supported here.');return}if(recognition){recognition.stop();recognition=null;log('Speech control off.');return}recognition=new SR();recognition.continuous=true;recognition.onresult=e=>{const text=e.results[e.results.length-1][0].transcript.toLowerCase();profile.input.speech++;if(/pulse|attack/.test(text))pulse();if(/interact|open/.test(text))interact();if(/phase/.test(text))phase();if(/geometry/.test(text))setCarrier(0);if(/semantic|meaning/.test(text))setCarrier(1);if(/rhythm/.test(text))setCarrier(2);save();log('Voice: '+text)};recognition.onend=()=>recognition=null;recognition.start();log('Speech control on. Browser/vendor speech services may be used.')}
const channel=('BroadcastChannel'in window)?new BroadcastChannel('decision-field-mmorpg-v2'):null;function broadcast(extra={}){channel?.postMessage({type:'state',id:player.id,name:player.name,x:player.x,y:player.y,level:player.level,...extra})}if(channel)channel.onmessage=e=>{const m=e.data;if(!m||m.id===player.id)return;if(m.type==='shout'){log(m.text);return}ghosts.set(m.id,{...m,last:performance.now()})};setInterval(()=>broadcast(),500);
function update(dt){state.t+=dt;state.eventT+=dt;if(state.eventT>state.eventEvery)mutateWorld();let ax=0,ay=0;if(keys.has('a')||keys.has('arrowleft'))ax--;if(keys.has('d')||keys.has('arrowright'))ax++;if(keys.has('w')||keys.has('arrowup'))ay--;if(keys.has('s')||keys.has('arrowdown'))ay++;if(ax||ay){const n=Math.hypot(ax,ay)||1;player.vx+=ax/n*.5;player.vy+=ay/n*.5;profile.moves++;profile.input.keyboard++}if(pointer.active){const dx=pointer.x-W/2,dy=pointer.y-H/2,n=Math.hypot(dx,dy)||1;player.vx+=dx/n*.28;player.vy+=dy/n*.28;profile.moves++;profile.input.pointer++}const max=player.phase>0?9:5.8;player.vx=Math.max(-max,Math.min(max,player.vx*.88));player.vy=Math.max(-max,Math.min(max,player.vy*.88));player.x+=player.vx*60*dt;player.y+=player.vy*60*dt;player.phase=Math.max(0,player.phase-dt);for(const m of mobs){if(m.hp<=0)continue;const dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1;m.x+=dx/d*m.speed*dt*state.chaos;m.y+=dy/d*m.speed*dt*state.chaos;if(d<m.r+12&&player.phase<=0){player.hp-=10*dt*state.chaos;if(player.hp<=0){player.hp=100;player.x=player.y=0;profile.failures++;log('You reformed at the origin. Failure preserved.');save()}}}for(let i=mobs.length-1;i>=0;i--)if(mobs[i].hp<=0)mobs.splice(i,1);while(mobs.length<55)addMob();if(player.xp>=100*player.level){player.xp-=100*player.level;player.level++;player.hp=100;log('LEVEL '+player.level+' — field capacity increased.')}for(const [id,g] of ghosts)if(performance.now()-g.last>3000)ghosts.delete(id)}
const sx=v=>v-player.x+W/2,sy=v=>v-player.y+H/2;function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(W/2,H/2,10,W/2,H/2,Math.max(W,H));g.addColorStop(0,['#112a33','#2d1530','#302713'][state.carrier]);g.addColorStop(1,'#030508');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const s of signals){const px=sx(s.x),py=sy(s.y);if(px<0||py<0||px>W||py>H)continue;ctx.fillStyle='#ffe66e';ctx.beginPath();ctx.arc(px,py,4+Math.sin(state.t*4+s.x)*1.5,0,Math.PI*2);ctx.fill()}for(const m of mobs){const px=sx(m.x),py=sy(m.y);if(px<-50||py<-50||px>W+50||py>H+50)continue;ctx.fillStyle=m.kind==='boss'?'#ff5364':m.kind==='beast'?'#ff9f64':'#7cf8ff';ctx.beginPath();ctx.arc(px,py,m.r,0,Math.PI*2);ctx.fill()}for(const g of ghosts.values()){ctx.fillStyle='#8cff9c';ctx.beginPath();ctx.arc(sx(g.x),sy(g.y),9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#caffd2';ctx.fillText(g.name,sx(g.x)-25,sy(g.y)-14)}ctx.fillStyle=state.fuzzball?'#ff7cf2':'#fff';ctx.beginPath();ctx.arc(W/2,H/2,12,0,Math.PI*2);ctx.fill();if(state.fuzzball){ctx.strokeStyle='#ff7cf2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(W/2,H/2,31+Math.sin(state.t*5)*5,0,Math.PI*2);ctx.stroke()}}
function hud(){ui('status').textContent=`${player.name} · LV ${player.level} · HP ${Math.round(player.hp)} · XP ${Math.round(player.xp)} · epoch ${state.epoch} · ${['geometry','semantic','rhythm'][state.carrier]}`;ui('event').textContent=`Next world mutation ${Math.max(0,state.eventEvery-state.eventT).toFixed(1)}s · chaos ${state.chaos.toFixed(2)} · ${ghosts.size+1} local shard player${ghosts.size===0?'':'s'}`;ui('quest').textContent=state.fuzzball?'Artifact resonance active. Recover signals to reopen Quantum Frontiers.':'Explore, survive, collect signals, change carriers, and watch for impossible coincidences.';if(state.fuzzball&&!state.frontier)openFrontier()}
ui('reset').onclick=()=>{localStorage.removeItem('df-mmorpg');location.reload()};function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();hud();requestAnimationFrame(frame)}requestAnimationFrame(frame);mutateWorld();if(state.fuzzball)openFrontier();log('World initialized. It will not stay still.');
