/* Continuous local playback and a bounded, read-only Conscience64 inspiration client. */
'use strict';
(()=>{
const E=window.MusilanguageEngine,$=id=>document.getElementById(id),catalog=E.catalog;
const state={ctx:null,master:null,playing:false,current:null,next:null,index:0,offset:0,epoch:0,planEpoch:0,cycle:0,baseSeed:640064,busy:false,preview:E.compose(catalog[0].id),receipt:null,connected:false,transitions:0};
const cache=new Map(),voices=new Set(),pending=new Map();let frame=null,connecting=false,requestNumber=0,renderCount=0;
const originURL=/^https?:$/.test(location.protocol)?new URL('../../',location.href):new URL('https://redogit.github.io/conscience64/');
const fmt=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
const say=s=>$('status').textContent=s;
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function makeItem(index,variation=false){const id=catalog[index].id,seed=variation&&id!=='carry-the-fire'?E.hash(state.baseSeed+':'+id+':'+state.cycle++):0;return {index,score:E.compose(id,seed),mix:$('mix').value,key:id+':'+seed+':'+$('mix').value};}
async function bufferFor(item){if(cache.has(item.key))return cache.get(item.key);renderCount++;const promise=E.renderer(item.score).render(E.levels(item.mix),22050);cache.set(item.key,promise);while(cache.size>2)cache.delete(cache.keys().next().value);try{return await promise;}catch(err){cache.delete(item.key);throw err;}}
function getVisible(){const c=state.ctx;return state.next&&c&&c.currentTime>=state.next.when?state.next:state.current;}
function time(){const item=getVisible();return item&&state.ctx?Math.max(0,Math.min(item.score.duration,state.ctx.currentTime-item.when+item.offset)):state.offset;}
function setMedia(score){if(!('mediaSession' in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:score.title,artist:'Musilanguage · Ryan April / AI-assisted',album:'Keep the Fire Moving'});navigator.mediaSession.playbackState=state.playing?'playing':'paused';}catch{}}
function show(score,index){state.preview=score;state.index=index;$('track-title').textContent=score.title;$('track-meta').textContent=score.key+' · '+score.bpm+' BPM · '+fmt(score.duration);$('variant').textContent=score.seed?'Variation seed '+score.seed:'Original arrangement';$('seek').max=score.duration;
 $('lyrics').replaceChildren();$('chapters').replaceChildren();for(const sec of score.sections){const box=document.createElement('section'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=sec.name;p.textContent=score.cues.filter(c=>c.section===sec.index).map(c=>c.text).join('\n');box.append(h,p);$('lyrics').append(box);const button=document.createElement('button');button.textContent=fmt(sec.start*60/score.bpm)+' · '+sec.name;button.onclick=()=>seek(sec.start*60/score.bpm);$('chapters').append(button);}
 for(const [i,button]of [...$('tracks').children].entries())button.setAttribute('aria-current',String(i===index));setMedia(score);
}
function unlock(){if(!state.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('This browser does not support Web Audio.');state.ctx=new AC();state.master=state.ctx.createGain();state.master.gain.value=Number($('volume').value)/100;state.master.connect(state.ctx.destination);}return state.ctx.resume();}
function clearVoices(){for(const v of voices){v.source.onended=null;try{v.source.stop();}catch{}v.source.disconnect();v.gain.disconnect();}voices.clear();state.current=null;state.next=null;}
function spawn(item,buffer,when,offset,epoch){const ctx=state.ctx,source=ctx.createBufferSource(),gain=ctx.createGain(),remaining=buffer.duration-offset,end=when+remaining,fade=Math.min(.7,remaining/3);source.buffer=buffer;source.connect(gain);gain.connect(state.master);gain.gain.setValueAtTime(0,when);gain.gain.linearRampToValueAtTime(1,when+fade);gain.gain.setValueAtTime(1,Math.max(when+fade,end-.75));gain.gain.linearRampToValueAtTime(0,end);const v={...item,buffer,source,gain,when,offset,end};voices.add(v);
 source.onended=()=>{voices.delete(v);source.disconnect();gain.disconnect();if(epoch!==state.epoch||state.current!==v)return;if(state.next){state.current=state.next;state.next=null;state.transitions++;show(state.current.score,state.current.index);prepareNext();}else{state.offset=v.score.duration;state.current=null;state.playing=false;$('play').textContent='Play again';say($('mode').value==='single'?'Track finished.':'Track finished before the next render was ready. Press Play to resume.');setMedia(v.score);}};
 source.start(when,offset);return v;
}
async function prepareNext(){const c=state.current,epoch=state.epoch,plan=++state.planEpoch;if(!c||$('mode').value==='single'){$('up-next').textContent='One-track mode: stop after this song.';return;}const item=makeItem((c.index+1)%catalog.length,$('mode').value==='mutate');$('up-next').textContent='Preparing: '+item.score.title;
 try{const buffer=await bufferFor(item);if(epoch!==state.epoch||plan!==state.planEpoch||state.current!==c)return;const when=Math.max(state.ctx.currentTime+.05,c.end-.7);state.next=spawn(item,buffer,when,0,epoch);$('up-next').textContent='Up next: '+item.score.title+(item.score.seed?' · new variation':'');}catch(err){if(epoch===state.epoch&&plan===state.planEpoch){$('up-next').textContent='Next track unavailable: '+err.message;}}
}
async function play(){if(state.busy)return;try{const resume=unlock();if(state.current){await resume;state.playing=true;$('play').textContent='Pause';say('Radio playing.');if(!state.next)prepareNext();return;}state.busy=true;$('play').disabled=true;const epoch=state.epoch;await resume;const score=state.preview.duration-state.offset<.1?E.compose(catalog[state.index].id,state.preview.seed):state.preview;if(state.offset>=score.duration-.1)state.offset=0;const item={index:state.index,score,mix:$('mix').value,key:score.id+':'+score.seed+':'+$('mix').value};say('Preparing local instruments…');const buffer=await bufferFor(item);if(epoch!==state.epoch)return;state.current=spawn(item,buffer,state.ctx.currentTime+.08,state.offset,epoch);state.playing=true;show(score,item.index);$('play').textContent='Pause';say('Playing. The next track is prepared ahead; Pause or Stop at any time.');prepareNext();}catch(err){say('Playback failed: '+err.message);state.playing=false;}finally{state.busy=false;$('play').disabled=false;}}
async function pause(){if(!state.ctx)return;await state.ctx.suspend();state.playing=false;$('play').textContent='Resume radio';say('Paused. Audio time and the scheduled queue are frozen.');setMedia(state.preview);}
function stop(){state.epoch++;state.planEpoch++;state.playing=false;clearVoices();state.offset=0;if(state.ctx)state.ctx.suspend().catch(()=>{});$('play').textContent='Play radio';$('up-next').textContent='Stopped. No music will start by itself.';say('Stopped.');setMedia(state.preview);tick();}
async function choose(index,autoplay=true){if(state.busy)return;stop();const item=makeItem((index+catalog.length)%catalog.length,$('mode').value==='mutate');show(item.score,item.index);state.offset=0;tick();if(autoplay)await play();}
async function seek(t){if(state.busy)return;const playing=state.playing,visible=getVisible(),score=visible?visible.score:state.preview,index=visible?visible.index:state.index;stop();show(score,index);state.offset=Math.max(0,Math.min(score.duration,Number(t)||0));tick();if(playing)await play();}
function resetNext(){state.planEpoch++;const next=state.next;if(next){next.source.onended=null;try{next.source.stop();}catch{}next.source.disconnect();next.gain.disconnect();voices.delete(next);state.next=null;}if(state.current)prepareNext();}
function tick(){const visible=getVisible();if(visible&&state.preview!==visible.score)show(visible.score,visible.index);const score=state.preview,t=time(),beat=t*score.bpm/60,sec=score.sections.find(s=>beat>=s.start&&beat<s.end)||score.sections.at(-1),cue=score.cues.filter(c=>c.b<=beat).at(-1);$('clock').textContent=fmt(t)+' / '+fmt(score.duration);if(document.activeElement!==$('seek'))$('seek').value=t;$('movement').textContent=sec.name+' / '+sec.sub;if(cue)$('lyric').textContent=cue.text;
 if('mediaSession'in navigator&&navigator.mediaSession.setPositionState)try{navigator.mediaSession.setPositionState({duration:score.duration,playbackRate:1,position:Math.min(score.duration,Math.max(0,t))});}catch{}
}
for(const [i,s]of catalog.entries()){const b=document.createElement('button');b.className='song';const title=document.createElement('span'),meta=document.createElement('small');title.textContent=String(i+1).padStart(2,'0')+' / '+s.title;meta.textContent=s.bpm+' BPM · '+s.key;b.append(title,meta);b.onclick=()=>choose(i);$('tracks').append(b);}
$('play').onclick=()=>state.playing?pause():play();$('stop').onclick=stop;$('next').onclick=()=>choose((getVisible()?.index??state.index)+1);$('prev').onclick=()=>choose((getVisible()?.index??state.index)-1);$('seek').onchange=()=>seek($('seek').value);$('volume').oninput=()=>{if(state.ctx)state.master.gain.setTargetAtTime(Number($('volume').value)/100,state.ctx.currentTime,.03);};$('mode').onchange=resetNext;$('mix').onchange=()=>{resetNext();say('Mix changed for upcoming tracks and WAV export. The current playing audio is unchanged.');};
$('reseed').onclick=()=>{const n=Number($('seed').value);if(!Number.isInteger(n)||n<0||n>4294967295){say('Enter a whole-number seed from 0 to 4294967295.');return;}state.baseSeed=n;state.cycle=0;$('mode').value='mutate';resetNext();say('Mutation radio enabled. New seed applies to upcoming arrangements.');};
$('wav').onclick=async()=>{const score=state.preview,mix=$('mix').value;$('wav').disabled=true;try{say('Rendering this arrangement to WAV…');const r=E.renderer(score),buffer=await r.render(E.levels(mix),44100);download(r.wav(buffer),score.id+(score.seed?'-'+score.seed:'')+'.wav','audio/wav');say('WAV exported: instrumental synth performance.');}catch(err){say('Export failed: '+err.message);}finally{$('wav').disabled=false;}};
$('midi').onclick=()=>{const s=state.preview;download(E.renderer(s).midi(),s.id+(s.seed?'-'+s.seed:'')+'.mid','audio/midi');say('MIDI exported with separate parts, tempo, meter and lyric cues.');};
// Only this iframe and this exact origin may answer a request. No received text is executed.
function ensureFrame(){if(frame)return frame;frame=document.createElement('iframe');frame.title='Conscience64 public research companion';frame.src=originURL.href;frame.loading='eager';frame.referrerPolicy='no-referrer';$('companion-host').append(frame);return frame;}
function acceptMessage(event){if(!frame||event.source!==frame.contentWindow||event.origin!==originURL.origin)return false;const m=event.data;if(!m||m.type!=='conscience64.api.result'||typeof m.id!=='string'||!pending.has(m.id))return false;const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);if(m.ok===true)p.resolve(m.result);else p.reject(Error(String(m.error||'Companion rejected request').slice(0,200)));return true;}
addEventListener('message',acceptMessage);
function rpc(method,args=[],timeout=1500){ensureFrame();const id='music-'+Date.now()+'-'+(++requestNumber);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('Conscience64 did not reply in time.'));},timeout);pending.set(id,{resolve,reject,timer});frame.contentWindow.postMessage({type:'conscience64.api',id,method,args},originURL.origin);});}
async function connect(){if(connecting)return;connecting=true;$('connect').disabled=true;$('connection-state').textContent='Connecting';$('connection-status').textContent='Loading the public companion and requesting its API…';try{ensureFrame();let stats;for(let i=0;i<12;i++){try{stats=await rpc('stats',[],800);break;}catch{if(i===11)throw Error('Conscience64 is unavailable here. Local radio remains available.');}}
 if(!stats||!Number.isInteger(stats.total)||stats.total<0)throw Error('Unexpected companion stats response.');const query=$('query').value.trim().slice(0,160);if(!query)throw Error('Enter an inspiration query.');const result=await rpc('search.simple',[query,{limit:8}],2500);if(!result||!Array.isArray(result.results))throw Error('Unexpected companion search response.');const sources=result.results.slice(0,8).map(r=>({id:String(r.uoid||r.logicalId||'').slice(0,160),label:String(r.label||r.logicalId||'Untitled').slice(0,240)}));
 if(!sources.length)throw Error('No public matches for this query. Existing seed retained.');const material=JSON.stringify(sources),seed=E.hash(material);state.baseSeed=seed;state.cycle=0;state.receipt={schema:'musilanguage/companion-inspiration/v1',retrievedAt:new Date().toISOString(),endpoint:originURL.href,methods:['stats','search.simple'],query,totalPublicObjects:stats.total,spaceUoid:stats.spaceUoid||null,sources,seed,hash:'FNV-1a-style uint32, non-cryptographic variation seed',mapping:'Source identities and labels seed local transposition, motif rotation and drum fills. Metadata is not composed audio, proof, or model reasoning.'};state.connected=true;$('seed').value=seed;$('mode').value='mutate';resetNext();$('connection-state').textContent='Connected';$('connection-status').textContent='Conscience64 replied: '+stats.total+' public objects; '+sources.length+' selected. Seed '+seed+' will shape upcoming variations.';$('sources').replaceChildren();for(const r of sources){const p=document.createElement('p');p.textContent=r.label+' — '+r.id;$('sources').append(p);}
 }catch(err){state.connected=false;$('connection-state').textContent='Local radio / no live link';$('connection-status').textContent=err.message;}finally{connecting=false;$('connect').disabled=false;}}
$('connect').onclick=connect;$('companion-panel').addEventListener('toggle',()=>{if($('companion-panel').open)ensureFrame();});$('receipt').onclick=()=>download(JSON.stringify(state.receipt||{status:'NO_COMPANION_SOURCE_USED',seed:state.baseSeed},null,2),'musilanguage-source-receipt.json','application/json');
if('mediaSession'in navigator){for(const [name,fn]of Object.entries({play,pause,stop,nexttrack:()=>choose(state.index+1),previoustrack:()=>choose(state.index-1),seekto:d=>seek(d.seekTime)}))try{navigator.mediaSession.setActionHandler(name,fn);}catch{}}
show(state.preview,0);tick();setInterval(tick,200);
window.MusilanguageRadio={version:'2.0.0',play,pause,stop,seek,choose,connect,rpc,acceptMessage,engine:E,get state(){return {playing:state.playing,index:state.index,position:time(),title:state.preview.title,seed:state.preview.seed,baseSeed:state.baseSeed,current:state.current?.score.id||null,next:state.next?.score.id||null,cacheEntries:cache.size,liveSources:voices.size,pendingRequests:pending.size,renderCount,connected:state.connected,transitions:state.transitions,busy:state.busy,receipt:state.receipt};}};
})();
