package org.rmaos.mingx;
import android.content.Context;import android.opengl.*;import android.os.*;import android.util.Log;import org.rmaos.mingx.generated.MiniGXGraph;import java.util.ArrayDeque;import java.io.InputStream;import java.nio.charset.StandardCharsets;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;
public final class MiniGXRenderer implements GLSurfaceView.Renderer {
 private static final String TAG="RMAOS-MiniGX";private final Context context;private final ArrayDeque<String> trace=new ArrayDeque<>();private final MiniGXGameState game=new MiniGXGameState();private MiniGXCircuit circuit;private int program,vao,uResolution,uTime,uControl,uTransform,uDigest,uRaySteps,uObserverCount,uPointCount,uBranchCount,uPulseRate,uFeedback,uBloom,uExposure,width=1,height=1,pulseNo=0;private int raySteps=48,observerCount=5,pointCount=96,branchCount=15;private long start;private float pulseRate=108,feedbackDecay=.94f,feedbackMix=.20f,bloom=1.15f,exposure=1.10f,feedbackState=0,yaw=0,pitch=0,zoom=1,load=0,pulse=0,reverse=1,transform=7;
 public MiniGXRenderer(Context c){context=c.getApplicationContext();} public MiniGXGameState game(){return game;}
 public synchronized void rotate(float dx,float dy){yaw+=dx;pitch=Math.max(-2f,Math.min(2f,pitch+dy));transform=4;record("SIDEWAYS");}
 public synchronized void scale(float f){zoom=Math.max(.55f,Math.min(2.2f,zoom*f));transform=f>=1?5:6;record(f>=1?"INWARD":"OUTWARD");}
 public synchronized void perturb(){pulse=1;load=Math.min(100,load+13);pulseNo++;transform=pulseNo%12;game.perturb(pulseNo%12);record("PERTURB:"+MiniGXGraph.DIGEST.substring(7,15)+":"+game.objectId());Vibrator v=(Vibrator)context.getSystemService(Context.VIBRATOR_SERVICE);if(v!=null&&v.hasVibrator())v.vibrate(VibrationEffect.createOneShot(22,VibrationEffect.DEFAULT_AMPLITUDE));}
 public synchronized void reverse(){reverse*=-1;yaw*=-1;transform=9;game.reverse();record("REVERSE/BBF:"+game.objectId());}
 public synchronized void recenter(){yaw=0;pitch=0;zoom=1;reverse=1;load*=.5f;feedbackState*=.5f;transform=11;game.recenter();record("RECENTER:"+game.objectId());}
 private synchronized void record(String op){if(trace.size()>=64)trace.removeFirst();trace.addLast(SystemClock.elapsedRealtime()+":"+op);}
 @Override public void onSurfaceCreated(GL10 gl,EGLConfig cfg){circuit=MiniGXCircuit.load(context);String vertex=circuit.param("W114_FIELD","vertex_shader"),fragment=circuit.param("W114_FIELD","shader");raySteps=circuit.intParam("W114_FIELD","ray_steps");observerCount=circuit.intParam("OBSERVER_CHANNELS","count");pointCount=circuit.intParam("GPU_POINTS","count");int depth=circuit.intParam("FRACTAL_BRANCHES","depth"),fan=circuit.intParam("FRACTAL_BRANCHES","fanout");branchCount=Math.min(15,Math.max(1,depth*fan));pulseRate=circuit.floatParam("PULSE_OSCILLATOR","rate");feedbackDecay=circuit.floatParam("FRAME_FEEDBACK","decay");feedbackMix=circuit.floatParam("FRAME_FEEDBACK","mix");bloom=circuit.floatParam("BLOOM_TONEMAP","bloom");exposure=circuit.floatParam("BLOOM_TONEMAP","exposure");program=link(loadAsset(vertex),loadAsset(fragment));int[]ids=new int[1];GLES30.glGenVertexArrays(1,ids,0);vao=ids[0];GLES30.glBindVertexArray(vao);uResolution=loc("uResolution");uTime=loc("uTime");uControl=loc("uControl");uTransform=loc("uTransform");uDigest=loc("uDigest");uRaySteps=loc("uRaySteps");uObserverCount=loc("uObserverCount");uPointCount=loc("uPointCount");uBranchCount=loc("uBranchCount");uPulseRate=loc("uPulseRate");uFeedback=loc("uFeedback");uBloom=loc("uBloom");uExposure=loc("uExposure");start=SystemClock.elapsedRealtimeNanos();GLES31.glDisable(GLES31.GL_DEPTH_TEST);record("BOOT:"+circuit.digest.substring(7,15));Log.i(TAG,"MiniGX ready nodes="+circuit.nodeCount+" edges="+circuit.edgeCount+" "+circuit.digest);}
 private int loc(String name){int x=GLES31.glGetUniformLocation(program,name);if(x<0)throw new IllegalStateException("MiniGX shader missing uniform "+name);return x;}
 @Override public void onSurfaceChanged(GL10 gl,int w,int h){width=Math.max(1,w);height=Math.max(1,h);GLES31.glViewport(0,0,width,height);}
 @Override public void onDrawFrame(GL10 gl){float t=(SystemClock.elapsedRealtimeNanos()-start)/1_000_000_000f,ly,lp,lz,lh,lpu,lr,lw,lf;synchronized(this){load=Math.max(0,load-.07f);pulse*=.94f;feedbackState=feedbackState*feedbackDecay+(pulse+load/100f*.08f)*feedbackMix;feedbackState=Math.max(0,Math.min(2,feedbackState));ly=yaw;lp=pitch;lz=zoom;lh=load;lpu=pulse;lr=reverse;lw=transform;lf=feedbackState;}GLES31.glUseProgram(program);GLES31.glUniform2f(uResolution,width,height);GLES31.glUniform1f(uTime,t);GLES31.glUniform4f(uControl,ly,lp,lz,lh/100f+lpu*.35f);GLES31.glUniform2f(uTransform,lw,lr);long d=Long.parseLong(MiniGXGraph.DIGEST.substring(7,15),16);GLES31.glUniform1f(uDigest,(d&0xffffL)/65535f);GLES31.glUniform1i(uRaySteps,raySteps);GLES31.glUniform1i(uObserverCount,observerCount);GLES31.glUniform1i(uPointCount,pointCount);GLES31.glUniform1i(uBranchCount,branchCount);GLES31.glUniform1f(uPulseRate,pulseRate);GLES31.glUniform1f(uFeedback,lf);GLES31.glUniform1f(uBloom,bloom);GLES31.glUniform1f(uExposure,exposure);GLES30.glBindVertexArray(vao);GLES31.glDrawArrays(GLES31.GL_TRIANGLES,0,3);}
 private static int compile(int type,String src){int s=GLES31.glCreateShader(type);GLES31.glShaderSource(s,src);GLES31.glCompileShader(s);int[]ok=new int[1];GLES31.glGetShaderiv(s,GLES31.GL_COMPILE_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("MiniGX shader compile: "+GLES31.glGetShaderInfoLog(s));return s;}
 private static int link(String vs,String fs){int p=GLES31.glCreateProgram(),v=compile(GLES31.GL_VERTEX_SHADER,vs),f=compile(GLES31.GL_FRAGMENT_SHADER,fs);GLES31.glAttachShader(p,v);GLES31.glAttachShader(p,f);GLES31.glLinkProgram(p);int[]ok=new int[1];GLES31.glGetProgramiv(p,GLES31.GL_LINK_STATUS,ok,0);if(ok[0]==0)throw new IllegalStateException("MiniGX program link: "+GLES31.glGetProgramInfoLog(p));GLES31.glDeleteShader(v);GLES31.glDeleteShader(f);return p;}
 private String loadAsset(String path){try(InputStream in=context.getAssets().open(path)){return new String(in.readAllBytes(),StandardCharsets.UTF_8);}catch(Exception e){throw new IllegalStateException("MiniGX shader asset load failed: "+path,e);}}
}
